window.COUNTRY_REGION_MAP = {
  // Major Europe (separate nodes)
  England: "England",
  Germany: "Germany",
  Spain: "Spain",
  France: "France",
  Italy: "Italy",
  Portugal: "Portugal",
  Netherlands: "Netherlands",
  Belgium: "Belgium",
  Turkey: "Turkey",
  Switzerland: "Switzerland",
  Denmark: "Denmark",
  Sweden: "Sweden",
  Norway: "Norway",
  Austria: "Austria",
  Croatia: "Croatia",
  Serbia: "Serbia",
  Poland: "Poland",

  // Small Europe -> Other Europe
  Andorra: "Other Europe",
  Albania: "Other Europe",
  Armenia: "Other Europe",
  Azerbaijan: "Other Europe",
  Belarus: "Other Europe",
  "Bosnia-Herzegovina": "Other Europe",
  Bulgaria: "Other Europe",
  Cyprus: "Other Europe",
  "Czech Republic": "Other Europe",
  Estonia: "Other Europe",
  Finland: "Other Europe",
  Georgia: "Other Europe",
  Greece: "Other Europe",
  Hungary: "Other Europe",
  Iceland: "Other Europe",
  Ireland: "Other Europe",
  Latvia: "Other Europe",
  Lithuania: "Other Europe",
  Luxembourg: "Other Europe",
  Malta: "Other Europe",
  Moldova: "Other Europe",
  Monaco: "Other Europe",
  Montenegro: "Other Europe",
  "North Macedonia": "Other Europe",
  "Northern Ireland": "Other Europe",
  "San Marino": "Other Europe",
  Slovakia: "Other Europe",
  Slovenia: "Other Europe",
  Scotland: "Other Europe",
  Wales: "Other Europe",
  Réunion: "Other Europe",
  Neukaledonien: "Other Europe",

  // South America
  Argentina: "South America",
  Brazil: "South America",
  Uruguay: "South America",
  Chile: "South America",
  Colombia: "South America",
  Paraguay: "South America",
  Peru: "South America",
  Ecuador: "South America",
  Bolivia: "South America",
  Venezuela: "South America",

  // Africa
  Algeria: "Africa",
  Angola: "Africa",
  "Burkina Faso": "Africa",
  Cameroon: "Africa",
  Congo: "Africa",
  "DR Congo": "Africa",
  Egypt: "Africa",
  Gabon: "Africa",
  Ghana: "Africa",
  Guinea: "Africa",
  "Ivory Coast": "Africa",
  "Cote d'Ivoire": "Africa",
  Mali: "Africa",
  Morocco: "Africa",
  Nigeria: "Africa",
  Senegal: "Africa",
  "South Africa": "Africa",
  Sudan: "Africa",
  Tunisia: "Africa",
  Zambia: "Africa",
  Zimbabwe: "Africa",

  // Asia + Middle East
  China: "Asia",
  Japan: "Asia",
  India: "Asia",
  Iran: "Asia",
  Iraq: "Asia",
  Israel: "Asia",
  Kazakhstan: "Asia",
  "Korea, South": "Asia",
  Kuwait: "Asia",
  Malaysia: "Asia",
  Qatar: "Asia",
  "Saudi Arabia": "Asia",
  "United Arab Emirates": "Asia",
  Uzbekistan: "Asia",

  // North America
  "United States": "North America",
  Canada: "North America",
  Mexico: "North America",
  "Costa Rica": "North America",
  Honduras: "North America",
  Panama: "North America",
  "Dominican Republic": "North America",

  // Oceania
  Australia: "Oceania",

  // Special categories
  "Career break": "Non-football",
  "Without Club": "Non-football",
  Retired: "Non-football",
  Unknown: "Unknown",
};
